# TruffleHog Configuration
# Scan the filesystem for secrets

[filesystem]
path = "."
exclude_paths = [
  ".next/**",
  "node_modules/**",
  "dist/**",
  "build/**",
  "coverage/**",
  ".git/**",
  "*.log",
  "*.tmp",
  "tests/results/**",
  "lint-results.json",
  "eslint-report.json",
  "complexity-report.json",
  "error-analysis.json",
  "**/test-results/**",
  "**/*-batch*.json",
  "**/current-errors-*.json"
]

# Enable entropy detection for high-confidence findings
detect_entropy = true
# Redact secrets in output
redact = true
# Fail on verified findings only (not unverified false positives)
fail_on_verified = true
# Only report verified and unknown results to reduce false positives
results = ["verified", "unknown"]
