[filesystem]
paths = ["."]
exclude_paths = [
  "node_modules/",
  ".next/",
  "dist/",
  "build/",
  "coverage/",
  ".git/",
  ".vscode/",
  ".nyc_output/",
  ".cache/",
  "public/*.map",
  "*.min.js",
  "*.bundle.js",
  "*.chunk.js"
]
