# TruffleHog Custom Configuration
# Reduces false positives by excluding common development patterns

detectors:
  - name: ExcludeESLintRules
    regex:
      pattern: "^\\s*\\b(?:ruleId|eslint|typescript-eslint|sonarjs|unicorn|no-unsafe).*"

  - name: ExcludeCodePatterns
    regex:
      pattern: "^(ReadableStream|food-truck-finder|DataProcessing|CachedFoodTruck|ExtractedFoodTruck|FirecrawlRequest|UpdateFoodTruck|handleFirecrawl|performDataQuality).*$"

  - name: ExcludeTestResults
    regex:
      pattern: "^(filePath|test-results|current-errors|food-truck-finder-poc).*$"
