name: "Scrape Food Trucks"
description: "GitHub Action to process pending scraping jobs for food trucks."
inputs:
  limit:
    description: "Maximum number of jobs to process."
    required: false
    default: "10"
runs:
  using: "node20"
  main: "index.js"
